package project.page;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project.Main;
import static project.Main.tbName_Product;
import project.Queries;

/**
 *
 * @author Dric
 */
public class PageStock extends javax.swing.JPanel {
    
//    public static enum ProductCategory{DAIRY, BAKING}
    
    /**
     * Creates new form FormBody
     */
    public PageStock() {
        initComponents();

        String query = "SELECT * FROM " + tbName_Product;

        try (Connection conn = Queries.getConnection(Main.dbName); PreparedStatement pst = Queries.prepareQuery(conn, query); ResultSet rs = pst.executeQuery()) {
            DefaultTableModel model = (DefaultTableModel) tableProduct.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                // Login success
                try {
                    // Assuming the ResultSet rs is already populated with data from the database
                    // Get the data from the ResultSet
                    String productID = rs.getString("product_ID"); // For the integer column, use getString()
                    String category = rs.getString("product_category");
                    String name = rs.getString("product_name");
                    String price = String.valueOf(rs.getFloat("product_price")); // Convert float to String
                    String quantity = String.valueOf(rs.getInt("product_quantity")); // Convert int to String
                    String uom = rs.getString("product_uom");
                    String deliveryDate = rs.getString("product_deliveryDate"); // Assume the date is formatted correctly
                    String expirationDate = rs.getString("product_expirationDate"); // Same as above
                    String image = "Image"; // For the BLOB, you can store a placeholder or image path

                    // Add the row to the model
                    model.addRow(new String[]{
                        productID, category, name, price, quantity, uom, deliveryDate, expirationDate, image
                    });

                } catch (SQLException e) {
                    e.printStackTrace(System.out);
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(System.out);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBody = new project.component.ShadowPanel();
        panelMain = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProduct = new project.swing.Table();

        setMaximumSize(new java.awt.Dimension(915, 544));
        setMinimumSize(new java.awt.Dimension(915, 544));
        setPreferredSize(new java.awt.Dimension(915, 544));

        panelBody.setMaximumSize(new java.awt.Dimension(915, 544));
        panelBody.setMinimumSize(new java.awt.Dimension(915, 544));
        panelBody.setPreferredSize(new java.awt.Dimension(915, 544));

        panelMain.setOpaque(false);

        jScrollPane2.setBorder(null);

        tableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Category", "Name", "Price", "Quantity", "Unit of Measure", "Delivery Date", "Expiry Date", "Image"
            }
        ));
        jScrollPane2.setViewportView(tableProduct);

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelBodyLayout = new javax.swing.GroupLayout(panelBody);
        panelBody.setLayout(panelBodyLayout);
        panelBodyLayout.setHorizontalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelBodyLayout.setVerticalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private project.component.ShadowPanel panelBody;
    private javax.swing.JPanel panelMain;
    private project.swing.Table tableProduct;
    // End of variables declaration//GEN-END:variables
}
