package project.page;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import project.Main;
import static project.Main.tbName_Product;
import project.Queries;
import project.swing.ScrollbarCustom;

/**
 *
 * @author Dric
 */
public class PageStock extends javax.swing.JPanel {

//    public static enum ProductCategory{DAIRY, BAKING}
    /**
     * Creates new form FormBody
     */
    public PageStock() {
        initComponents();
//        scrollProduct.setVerticalScrollBar(new ScrollbarCustom());
//        scrollProduct.setHorizontalScrollBar(new ScrollbarCustom());

        tableProduct.getColumnModel().getColumn(0).setPreferredWidth(40);
        tableProduct.getColumnModel().getColumn(1).setPreferredWidth(175);
        tableProduct.getColumnModel().getColumn(2).setPreferredWidth(200);
        tableProduct.getColumnModel().getColumn(3).setPreferredWidth(80);
        tableProduct.getColumnModel().getColumn(4).setPreferredWidth(80);
        tableProduct.getColumnModel().getColumn(6).setPreferredWidth(100);
        tableProduct.getColumnModel().getColumn(7).setPreferredWidth(100);
        tableProduct.getColumnModel().getColumn(8).setPreferredWidth(100);
        tableProduct.getColumnModel().getColumn(9).setPreferredWidth(100);
        tableProduct.getColumnModel().getColumn(10).setPreferredWidth(150);
        tableProduct.setAutoResizeMode(JTable.AUTO_RESIZE_OFF );
        refreshTableStock();
    }

    public final void refreshTableStock() {
        String query = "SELECT * FROM " + tbName_Product;

        try (Connection conn = Queries.getConnection(Main.dbName); PreparedStatement pst = Queries.prepareQuery(conn, query); ResultSet rs = pst.executeQuery()) {
            DefaultTableModel model = (DefaultTableModel) tableProduct.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                try {
                    String productID = rs.getString("product_ID");
                    String category = rs.getString("product_category");
                    String name = rs.getString("product_name");
                    String price = String.valueOf(rs.getFloat("product_price"));
                    String quantity = String.valueOf(rs.getInt("product_quantity"));
                    String totalPrice = String.valueOf(rs.getFloat("product_totalPrice"));
                    String uom = rs.getString("product_uom");
                    String deliveryDate = rs.getString("product_deliveryDate");
                    String expirationDate = rs.getString("product_expirationDate");
                    String image = "Image";
                    String employeeID = rs.getString("employee_ID");

                    model.addRow(new String[]{
                        productID, category, name, price, quantity, totalPrice, uom, deliveryDate, expirationDate, image, employeeID
                    });

                } catch (SQLException e) {
                    e.printStackTrace(System.out);
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(System.out);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBody = new project.component.ShadowPanel();
        panelMain = new javax.swing.JPanel();
        scrollProduct = new javax.swing.JScrollPane();
        tableProduct = new project.swing.Table();

        setMaximumSize(new java.awt.Dimension(915, 544));
        setMinimumSize(new java.awt.Dimension(915, 544));
        setPreferredSize(new java.awt.Dimension(915, 544));

        panelBody.setMaximumSize(new java.awt.Dimension(915, 544));
        panelBody.setMinimumSize(new java.awt.Dimension(915, 544));
        panelBody.setPreferredSize(new java.awt.Dimension(915, 544));

        panelMain.setOpaque(false);

        scrollProduct.setBorder(null);

        tableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Category", "Name", "Price", "Quantity", "Total Price", "Unit of Measure", "Delivery Date", "Expiry Date", "Image", "Employee"
            }
        ));
        scrollProduct.setViewportView(tableProduct);

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelBodyLayout = new javax.swing.GroupLayout(panelBody);
        panelBody.setLayout(panelBodyLayout);
        panelBodyLayout.setHorizontalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        panelBodyLayout.setVerticalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private project.component.ShadowPanel panelBody;
    private javax.swing.JPanel panelMain;
    private javax.swing.JScrollPane scrollProduct;
    private project.swing.Table tableProduct;
    // End of variables declaration//GEN-END:variables
}
