package project.search;

import project.Main;
import project.Queries;
import project.page.*;

/**
 *
 * @author Dric
 */
public class SearchComboBox extends javax.swing.JPanel {

    public enum EnumComboBox {
        BRAND_DELIVERY,
        BRAND_ITEM,
        CATEGORY_DELIVERY,
        CATEGORY_ITEM,
    }
    
    public EnumComboBox selectedSearch;

    /**
     * Creates new form FormBody
     */
    public SearchComboBox() {
        initComponents();
    }

    public void repopulateComboBox(EnumComboBox searchEnum) {
        if (null != searchEnum) {
            String query = null, column_name = null;
            switch (searchEnum) {
                case BRAND_DELIVERY: {
                    column_name = "product_brand";
                    query = "SELECT DISTINCT " + column_name + " FROM " + Main.tbName_ProductStock;
                    break;
                }
                case BRAND_ITEM: {
                    column_name = "product_brand";
                    query = "SELECT DISTINCT " + column_name + " FROM " + Main.tbName_ProductItem;
                    break;
                }
                case CATEGORY_DELIVERY: {
                    column_name = "product_category";
                    query = "SELECT DISTINCT " + column_name + " FROM " + Main.tbName_ProductStock;
                    break;
                }
                case CATEGORY_ITEM: {
                    column_name = "product_category";
                    query = "SELECT DISTINCT " + column_name + " FROM " + Main.tbName_ProductItem;
                    break;
                }
                default:
                    break;
            }
            Queries.repopulateComboBox(comboBox, column_name, query);
        }
    }

    public String getSelectedComboBox() {
        return (String) comboBox.getSelectedItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateSearchStart = new project.date.DateChooser();
        dateSearchEnd = new project.date.DateChooser();
        panelMain = new javax.swing.JPanel();
        comboBox = new javax.swing.JComboBox<>();

        dateSearchStart.setDateFormat("yyyy-MM-dd");

        dateSearchEnd.setDateFormat("yyyy-MM-dd");

        setMaximumSize(new java.awt.Dimension(393, 35));
        setMinimumSize(new java.awt.Dimension(393, 35));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(393, 35));

        panelMain.setMaximumSize(new java.awt.Dimension(520, 35));
        panelMain.setMinimumSize(new java.awt.Dimension(520, 35));
        panelMain.setOpaque(false);

        comboBox.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBox;
    private project.date.DateChooser dateSearchEnd;
    private project.date.DateChooser dateSearchStart;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
