package project.search;

import java.awt.Color;
import project.WindowUtils;

/**
 *
 * @author Dric
 */
public class SearchComboBoxField extends javax.swing.JPanel {

    public enum EnumComboBoxField {
        LIMIT_VALUE,
        LIMIT_RETAIL_PRICE,
        LIMIT_REMAINING_QUANTITY,
    }

    public EnumComboBoxField selectedSearch;

    /**
     * Creates new form FormBody
     */
    public SearchComboBoxField() {
        initComponents();
        WindowUtils.setTransparentFrame(textField);
    }

    public void repopulateComboBox(EnumComboBoxField searchEnum) {
        if (null != searchEnum) {
            switch (searchEnum) {
                case LIMIT_VALUE: {
                    comboBox.removeAllItems();
                    comboBox.addItem("Greater Than");
                    comboBox.addItem("Greater Than or Equal To");
                    comboBox.addItem("Lesser Than");
                    comboBox.addItem("Lesser Than or Equal To");
                    comboBox.addItem("Equal To");
                    break;
                }
                default:
                    break;
            }
        }
    }

    public String getSelectedComboBox() {
        return (String) comboBox.getSelectedItem();
    }

    public String getSelectedTextField() {
        return textField.getText();
    }

    public void setSelectedTextField(String string) {
        textField.setText(string);
        textField.setForeground(new Color(0, 0, 0));
    }

    public String getLimitValueOperator(String string) {
        String operator = null;

        switch (string) {
            case "Greater Than":
                operator = ">";
                break;
            case "Greater Than or Equal To":
                operator = ">=";
                break;
            case "Lesser Than":
                operator = "<";
                break;
            case "Lesser Than or Equal To":
                operator = "<=";
                break;
            case "Equal To":
                operator = "=";
                break;
            default:
                break;
        }
        return operator;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        comboBox = new javax.swing.JComboBox<>();
        textField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setMaximumSize(new java.awt.Dimension(393, 35));
        setMinimumSize(new java.awt.Dimension(393, 35));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(393, 35));

        panelMain.setMaximumSize(new java.awt.Dimension(520, 35));
        panelMain.setMinimumSize(new java.awt.Dimension(520, 35));
        panelMain.setOpaque(false);

        comboBox.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        textField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        textField.setForeground(new java.awt.Color(153, 153, 153));
        textField.setText("Enter Value");
        textField.setBorder(null);
        textField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldFocusLost(evt);
            }
        });
        textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldActionPerformed(evt);
            }
        });
        textField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(textField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldActionPerformed

    }//GEN-LAST:event_textFieldActionPerformed

    private void textFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldKeyTyped
        if (selectedSearch == EnumComboBoxField.LIMIT_VALUE) {
            WindowUtils.enforceDigits(evt);
        }
    }//GEN-LAST:event_textFieldKeyTyped

    private void textFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldFocusGained
        WindowUtils.setDefaultField(textField, "Enter Value", WindowUtils.FieldFocus.GAINED, Color.BLACK);
    }//GEN-LAST:event_textFieldFocusGained

    private void textFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldFocusLost
        WindowUtils.setDefaultField(textField, "Enter Value", WindowUtils.FieldFocus.LOST, Color.BLACK);
    }//GEN-LAST:event_textFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelMain;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
