package project.search;

import javax.swing.JTextField;
import project.WindowUtils;

/**
 *
 * @author Dric
 */
public class SearchDeliveryDateBetween extends javax.swing.JPanel {

    /**
     * Creates new form FormBody
     */
    public SearchDeliveryDateBetween() {
        initComponents();
        WindowUtils.setTransparentFrame(fieldSearchDateStart, fieldSearchDateEnd);
    }

    public JTextField getFieldSearchDateStart() {
        return fieldSearchDateStart;
    }

    public JTextField getFieldSearchDateEnd() {
        return fieldSearchDateEnd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateSearchStart = new project.date.DateChooser();
        dateSearchEnd = new project.date.DateChooser();
        panelMain = new javax.swing.JPanel();
        btnSearchDateStart = new javax.swing.JButton();
        fieldSearchDateStart = new javax.swing.JTextField();
        fieldSearchDateEnd = new javax.swing.JTextField();
        btnSearchDateEnd = new javax.swing.JButton();

        dateSearchStart.setDateFormat("yyyy-MM-dd");
        dateSearchStart.setTextRefernce(fieldSearchDateStart);

        dateSearchEnd.setDateFormat("yyyy-MM-dd");
        dateSearchEnd.setTextRefernce(fieldSearchDateEnd);

        setMaximumSize(new java.awt.Dimension(520, 35));
        setMinimumSize(new java.awt.Dimension(520, 35));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(520, 35));

        panelMain.setMaximumSize(new java.awt.Dimension(520, 35));
        panelMain.setMinimumSize(new java.awt.Dimension(520, 35));
        panelMain.setOpaque(false);

        btnSearchDateStart.setText("...");
        btnSearchDateStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchDateStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDateStartActionPerformed(evt);
            }
        });

        fieldSearchDateStart.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        fieldSearchDateStart.setBorder(null);
        fieldSearchDateStart.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fieldSearchDateStart.setFocusable(false);
        fieldSearchDateStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSearchDateStartActionPerformed(evt);
            }
        });

        fieldSearchDateEnd.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        fieldSearchDateEnd.setBorder(null);
        fieldSearchDateEnd.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fieldSearchDateEnd.setFocusable(false);

        btnSearchDateEnd.setText("...");
        btnSearchDateEnd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchDateEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDateEndActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldSearchDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchDateStart)
                .addGap(41, 41, 41)
                .addComponent(fieldSearchDateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchDateEnd)
                .addContainerGap())
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldSearchDateStart)
                    .addComponent(fieldSearchDateEnd)
                    .addComponent(btnSearchDateStart)
                    .addComponent(btnSearchDateEnd))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchDateStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDateStartActionPerformed
        dateSearchStart.showPopup();
    }//GEN-LAST:event_btnSearchDateStartActionPerformed

    private void fieldSearchDateStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSearchDateStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSearchDateStartActionPerformed

    private void btnSearchDateEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDateEndActionPerformed
        dateSearchEnd.showPopup();
    }//GEN-LAST:event_btnSearchDateEndActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchDateEnd;
    private javax.swing.JButton btnSearchDateStart;
    private project.date.DateChooser dateSearchEnd;
    private project.date.DateChooser dateSearchStart;
    private javax.swing.JTextField fieldSearchDateEnd;
    private javax.swing.JTextField fieldSearchDateStart;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
