package project.search;

import project.Main;
import project.Queries;

/**
 *
 * @author Dric
 */
public class SearchEmpty extends javax.swing.JPanel {

    /**
     * Creates new form FormBody
     */
    public SearchEmpty() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateSearchStart = new project.date.DateChooser();
        dateSearchEnd = new project.date.DateChooser();
        panelMain = new javax.swing.JPanel();

        dateSearchStart.setDateFormat("yyyy-MM-dd");

        dateSearchEnd.setDateFormat("yyyy-MM-dd");

        setMaximumSize(new java.awt.Dimension(393, 35));
        setMinimumSize(new java.awt.Dimension(393, 35));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(393, 35));

        panelMain.setMaximumSize(new java.awt.Dimension(520, 35));
        panelMain.setMinimumSize(new java.awt.Dimension(520, 35));
        panelMain.setOpaque(false);

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private project.date.DateChooser dateSearchEnd;
    private project.date.DateChooser dateSearchStart;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
